name             'drivers'
maintainer       'Roderik van der Veer'
maintainer_email 'roderik@vanderveer.be'
license          'apache 2.0'
description      'Installs/Configures drivers'
version          '0.1.1'
